---
# this script will install lxd container
- hosts: localhost
  become: yes
  gather_facts: yes
  ignore_errors: true
  
  tasks:
  - name: Create a started test-centos7 container
    include: play/test-centos7.yml
    tags: test-centos7

  - name: Create a started test-centos8 container
    include: play/test-centos8.yml
    tags: test-centos8

  - name: Create a started test-ubuntu16 container
    include: play/test-ubuntu16.yml
    tags: test-ubuntu16

  - name: Create a started test-ubuntu18 container
    include: play/test-ubuntu18.yml
    tags: test-ubuntu18

  - name: Create a started test-ubuntu20 container
    include: play/test-ubuntu20.yml
    tags: test-ubuntu20

  - name: Create a started test-archlinux container
    include: play/test-archlinux.yml
    tags: test-archlinux

  - name: Create a started test-opensuse15 container
    include: play/test-opensuse15.yml
    tags: test-opensuse15

  - name: Create a started test-rockylinux8 container
    include: play/test-rockylinux8.yml
    tags: test-rockylinux8
